/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Router */

#ifndef _Included_jni_Router
#define _Included_jni_Router
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     jni_Router
	* Method:    InvokeNetMethod
	* Signature: (Ljni/Request;)Ljni/Response;
	*/
	JNIEXPORT jobject JNICALL Java_jni_Router_InvokeNetMethod
		(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif